skiplist-build:
  stage: build
  image: gcc
  only:
    changes:
      - ".gitlab-ci.yml"
      - "src/*"
  script:
    - cd src
    - make test_skipliste
  artifacts:
    paths:
      - src/test_skipliste

skiplist-test:
  stage: test
  only:
    changes:
      - ".gitlab-ci.yml"
      - "src/*"
  script:
    - src/test_skipliste
  dependencies:
    - skiplist-build

tikz-build:
  stage: build
  image: 
    name: aergus/latex
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - cd images
    - find . -type f -name "*.tex" -exec latexmk -pdf {} \;
  only:
    changes:
      - ".gitlab-ci.yml"
      - "images/*.tex"
  artifacts:
    paths:
      - "images/*.pdf"
